package APIConnection;


/**
* APIConnection/_ClientImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public abstract class _ClientImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements APIConnection.Client, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ClientImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("receiveBasicUserData", new java.lang.Integer (0));
    _methods.put ("receiveRepoDetails", new java.lang.Integer (1));
    _methods.put ("receiveDeveloperLanguages", new java.lang.Integer (2));
    _methods.put ("receiveRepoCount", new java.lang.Integer (3));
    _methods.put ("receiveCloneUrl", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // APIConnection/Client/receiveBasicUserData
       {
         String jsonShowInfo = in.read_string ();
         this.receiveBasicUserData (jsonShowInfo);
         out = $rh.createReply();
         break;
       }

       case 1:  // APIConnection/Client/receiveRepoDetails
       {
         String jsonShowInfo = in.read_string ();
         this.receiveRepoDetails (jsonShowInfo);
         out = $rh.createReply();
         break;
       }

       case 2:  // APIConnection/Client/receiveDeveloperLanguages
       {
         String jsonShowInfo = in.read_string ();
         this.receiveDeveloperLanguages (jsonShowInfo);
         out = $rh.createReply();
         break;
       }

       case 3:  // APIConnection/Client/receiveRepoCount
       {
         String jsonShowInfo = in.read_string ();
         this.receiveRepoCount (jsonShowInfo);
         out = $rh.createReply();
         break;
       }

       case 4:  // APIConnection/Client/receiveCloneUrl
       {
         String jsonShowInfo = in.read_string ();
         this.receiveCloneUrl (jsonShowInfo);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:APIConnection/Client:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ClientImplBase
