package APIConnection;


/**
* APIConnection/Client_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public class Client_Tie extends _ClientImplBase
{

  // Constructors
  public Client_Tie ()
  {
  }

  public Client_Tie (APIConnection.ClientOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void receiveBasicUserData (String jsonShowInfo)
  {
    _impl.receiveBasicUserData(jsonShowInfo);
  } // receiveBasicUserData

  public void receiveRepoDetails (String jsonShowInfo)
  {
    _impl.receiveRepoDetails(jsonShowInfo);
  } // receiveRepoDetails

  public void receiveDeveloperLanguages (String jsonShowInfo)
  {
    _impl.receiveDeveloperLanguages(jsonShowInfo);
  } // receiveDeveloperLanguages

  public void receiveRepoCount (String jsonShowInfo)
  {
    _impl.receiveRepoCount(jsonShowInfo);
  } // receiveRepoCount

  public void receiveCloneUrl (String jsonShowInfo)
  {
    _impl.receiveCloneUrl(jsonShowInfo);
  } // receiveCloneUrl

  private APIConnection.ClientOperations _impl;

} // class Client_Tie
