package APIConnection;

/**
* APIConnection/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public APIConnection.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (APIConnection.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = APIConnection.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    APIConnection.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return APIConnection.ClientHelper.type ();
  }

}
