package APIConnection;


/**
* APIConnection/GitHubOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public interface GitHubOperations 
{
  void getBasicUserData (String userName, APIConnection.Client client);
  void getRepoDetails (String userName, String repo, APIConnection.Client client);
  void getDeveloperLanguages (String userName, String repo, APIConnection.Client client);
  void getRepoCount (String userName, APIConnection.Client client);
  void getCloneUrl (String userName, String repoName, APIConnection.Client client);
} // interface GitHubOperations
