package APIConnection;


/**
* APIConnection/GitHub_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public class GitHub_Tie extends _GitHubImplBase
{

  // Constructors
  public GitHub_Tie ()
  {
  }

  public GitHub_Tie (APIConnection.GitHubOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void getBasicUserData (String userName, APIConnection.Client client)
  {
    _impl.getBasicUserData(userName, client);
  } // getBasicUserData

  public void getRepoDetails (String userName, String repo, APIConnection.Client client)
  {
    _impl.getRepoDetails(userName, repo, client);
  } // getRepoDetails

  public void getDeveloperLanguages (String userName, String repo, APIConnection.Client client)
  {
    _impl.getDeveloperLanguages(userName, repo, client);
  } // getDeveloperLanguages

  public void getRepoCount (String userName, APIConnection.Client client)
  {
    _impl.getRepoCount(userName, client);
  } // getRepoCount

  public void getCloneUrl (String userName, String repoName, APIConnection.Client client)
  {
    _impl.getCloneUrl(userName, repoName, client);
  } // getCloneUrl

  private APIConnection.GitHubOperations _impl;

} // class GitHub_Tie
