package APIConnection;

/**
* APIConnection/GitHubHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from API.idl
* Thursday, 31 March 2016 12:29:02 o'clock BST
*/

public final class GitHubHolder implements org.omg.CORBA.portable.Streamable
{
  public APIConnection.GitHub value = null;

  public GitHubHolder ()
  {
  }

  public GitHubHolder (APIConnection.GitHub initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = APIConnection.GitHubHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    APIConnection.GitHubHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return APIConnection.GitHubHelper.type ();
  }

}
